# Generated by Django 4.0.4 on 2022-04-23 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('house', models.CharField(blank=True, max_length=8, null=True)),
                ('apartment', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('elevator', models.BooleanField(default=False, null=True)),
                ('comment', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddressTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('street', models.CharField(blank=True, max_length=128, null=True)),
                ('house', models.CharField(blank=True, max_length=8, null=True)),
                ('apartment', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('elevator', models.BooleanField(default=False, null=True)),
                ('comment', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofa', models.PositiveSmallIntegerField(default=0, null=True)),
                ('bed', models.PositiveSmallIntegerField(default=0, null=True)),
                ('table', models.PositiveSmallIntegerField(default=0, null=True)),
                ('armchair', models.PositiveSmallIntegerField(default=0, null=True)),
                ('chair', models.PositiveSmallIntegerField(default=0, null=True)),
                ('cabinet', models.PositiveSmallIntegerField(default=0, null=True)),
                ('other_m3', models.PositiveSmallIntegerField(default=0, null=True)),
                ('other_heavy_goods', models.PositiveSmallIntegerField(default=0, null=True)),
                ('fragile', models.BooleanField(default=False, null=True)),
                ('comment', models.TextField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=14, null=True)),
                ('my_price', models.PositiveSmallIntegerField(null=True)),
                ('movers', models.BooleanField(default=False, null=True)),
                ('packers', models.BooleanField(default=False, null=True)),
                ('all_inclusive', models.BooleanField(default=False, null=True)),
                ('comment', models.TextField(max_length=250, null=True)),
                ('address_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.addressfrom')),
                ('address_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.addressto')),
                ('stuff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.stuff')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
